[package]
name = "hilbert-geometry"
version = "0.1.0"
edition = "2024"
description = "Hilbert-encoded geometries"
license = "MIT"
repository = "https://github.com/alamminsalo/hilbert-geometry"

[dependencies]
bincode = "2.0.1"
geo-types = "0.7.16"
hilbert_2d = "1.1.0"
